#!/usr/bin/env bun
/* Export a deterministic demo seed from a live projection.
 *
 * Run by a maintainer with a reader URL, never by a person cloning the
 * repository — the point of the seed is that they need no credential at all.
 * The output is committed.
 *
 * Everything is exported whole except `native_records`, which is 38 MB of
 * source corpus across nearly twenty thousand rows. That table is filtered to
 * the Problems the demo actually opens plus every record any retained binding
 * points at, which keeps the seed small enough to read in a diff while leaving
 * the catalogue internally consistent: the row count a page reports is the row
 * count it can show.
 *
 *   bun scripts/demo/export-seed.mjs > scripts/demo/seed.sql
 */
import { neon } from "@neondatabase/serverless";

const DEMO_PROBLEMS = ["321", "94", "1"];

import { readFileSync } from "node:fs";
import { resolve } from "node:path";
const repositoryRoot = resolve(import.meta.dirname, "../..");
const read = (path) => readFileSync(resolve(repositoryRoot, path), "utf8");

const url = process.env.VELA_PROJECTION_DATABASE_URL;
if (!url) throw new Error("VELA_PROJECTION_DATABASE_URL is required to export a seed");
const sql = neon(url);
const rows = async (text, params = []) => {
  const result = await sql.query(text, params);
  return Array.isArray(result) ? result : result.rows;
};

function literal(value) {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "NULL";
  if (typeof value === "boolean") return value ? "TRUE" : "FALSE";
  if (value instanceof Date) return `'${value.toISOString()}'`;
  if (Array.isArray(value) || typeof value === "object") {
    return `'${JSON.stringify(value).replaceAll("'", "''")}'::jsonb`;
  }
  return `'${String(value).replaceAll("'", "''")}'`;
}

/* Arrays land as JS arrays whichever column type they came from, so the target
   type is read from the catalogue rather than guessed from the value. */
async function columnTypes(table) {
  /* Generated columns refuse an explicit value, so they are left out and
     recomputed on insert — `search_documents.search_text` is one. */
  const described = await rows(
    `select column_name, udt_name, data_type from information_schema.columns
     where table_schema = 'projection' and table_name = $1
       and is_generated = 'NEVER' and identity_generation is null
     order by ordinal_position`,
    [table],
  );
  return described.map((column) => ({
    name: column.column_name,
    array: column.data_type === "ARRAY",
    udt: String(column.udt_name).replace(/^_/u, ""),
  }));
}

function value(column, raw) {
  if (raw === null || raw === undefined) return "NULL";
  if (column.array) {
    const items = Array.isArray(raw) ? raw : [raw];
    return `ARRAY[${items.map((item) => literal(item)).join(", ")}]::${column.udt}[]`;
  }
  if (column.udt === "jsonb" || column.udt === "json") {
    return `'${JSON.stringify(raw).replaceAll("'", "''")}'::${column.udt}`;
  }
  return literal(raw);
}

async function emit(table, where = "", params = []) {
  const columns = await columnTypes(table);
  const data = await rows(`select * from projection.${table} ${where}`, params);
  if (!data.length) {
    process.stdout.write(`-- projection.${table}: no rows\n\n`);
    return 0;
  }
  const names = columns.map((column) => `"${column.name}"`).join(", ");
  process.stdout.write(`-- projection.${table}: ${data.length} rows\n`);
  for (const row of data) {
    const values = columns.map((column) => value(column, row[column.name])).join(", ");
    process.stdout.write(`INSERT INTO projection.${table} (${names}) VALUES (${values});\n`);
  }
  process.stdout.write("\n");
  return data.length;
}

const release = (await rows("select release_root from projection.current_release limit 1"))[0];
if (!release) throw new Error("the projection has no current release");

process.stdout.write(`-- Deterministic demo seed for problems.science.
-- Generated by scripts/demo/export-seed.mjs from projection release
-- ${release.release_root}
--
-- Loaded by \`bun run dev:demo\` into an in-process Postgres. Every row here is
-- a real projected row: the Erdős 321 correction this demo turns on was decided
-- and signed in the vela-science/math repository, not written by hand.

`);

/* Ordered so a reader can follow it: the release and its manifest, then the
   repository, then the scientific records, then the source corpus. */
const whole = [
  "releases", "current_release", "schema_migrations", "repositories",
  "claims", "reviews", "submissions", "verifications",
  "commits", "repository_revisions", "repository_transitions",
  "graph_nodes", "graph_edges", "frontier_edges", "search_documents",
  "source_declarations", "source_observations", "release_sources",
  "repository_source_bindings",
  "fc_frontier_snapshots", "fc_frontier_families", "fc_frontier_repairs",
];

const counts = {};
for (const table of whole) counts[table] = await emit(table);

/* The one filtered table, and the only place this script could get the answer
   wrong quietly.
 *
 * Guessing native ids by pattern does not work: each source names the same
 * Problem in its own scheme — `erdos:321`, `vibemathed:erdos-321`,
 * `erdos-ai-wiki:12:a2032100…`. A seed built from `erdos:%` loaded fine and then
 * the page refused with "Problem source set is missing reviewed occurrence",
 * which is the resolver correctly noticing an incomplete set.
 *
 * So the occurrences are read from the resolver configuration the application
 * itself uses. Every occurrence of every entity is retained — 37 rows across
 * every published Problem — plus the Lean declarations under each Erdős
 * namespace, which is what the Sources view previews. */
const resolution = JSON.parse(read("packages/projection-data/config/problem-resolution.v1.json"));
const occurrences = [];
const collect = (node) => {
  if (Array.isArray(node)) return node.forEach(collect);
  if (!node || typeof node !== "object") return;
  if (typeof node.source_id === "string" && typeof node.native_id === "string") occurrences.push(node.native_id);
  Object.values(node).forEach(collect);
};
collect(resolution);

counts.native_records = await emit(
  "native_records",
  `where native_id = any($1::text[])
      or native_id like any($2::text[])
      or row_root in (select native_record_root from projection.repository_source_bindings)`,
  [[...new Set(occurrences)], DEMO_PROBLEMS.map((problem) => `Erdos${problem}.%`)],
);

process.stderr.write(`${JSON.stringify({ release_root: release.release_root, counts }, null, 1)}\n`);
