import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const MDX_PATH = path.resolve(import.meta.dirname, "../src/content/essays/constellations/index.mdx");
const TEX_PATH = path.resolve(import.meta.dirname, "../docs/constellations/constellations.tex");

const SECTION_GLYPHS: Record<string, string> = {
  "The Inheritance": "\\glyphinheritance",
  "The Pattern": "\\glyphpattern",
  "The Foundation": "\\glyphsoftware",
  "The Constellation": "\\glyphconstellation",
  "The Gigafactory": "\\glyphgigafactory",
};

const META_KEYS = [
  "title",
  "subtitle",
  "description",
  "author",
  "date",
  "readingTime",
  "canonicalPath",
  "pdfPath",
  "summaryPath",
  "researchPath",
] as const;

type MetaKey = (typeof META_KEYS)[number];
type Meta = Record<MetaKey, string>;

const readText = (filePath: string): string =>
  readFileSync(filePath, "utf8").replaceAll("\r\n", "\n");

const escapeLatex = (value: string): string =>
  value
    .replaceAll("\\", "\\textbackslash{}")
    .replaceAll("{", "\\{")
    .replaceAll("}", "\\}")
    .replaceAll("&", "\\&")
    .replaceAll("%", "\\%")
    .replaceAll("$", "\\$")
    .replaceAll("#", "\\#")
    .replaceAll("_", "\\_");

const parseMeta = (source: string): { meta: Meta; body: string } => {
  const match = source.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) {
    throw new Error("MDX file is missing frontmatter.");
  }

  const frontmatter = match[1];
  const body = match[2];
  const meta = {} as Meta;

  for (const key of META_KEYS) {
    const keyMatch = frontmatter.match(new RegExp(`^${key}:\\s*\"([^\"]*)\"$`, "m"));
    meta[key] = keyMatch?.[1] ?? "";
  }

  return { meta, body };
};

const parseAttributes = (source: string): Record<string, string> => {
  const attrs: Record<string, string> = {};
  for (const match of source.matchAll(/(\w+)="([^"]*)"/g)) {
    attrs[match[1]] = match[2];
  }
  return attrs;
};

const renderSection = (title: string): string => {
  const glyph = SECTION_GLYPHS[title] ?? "";
  const suffix = glyph ? ` \\hfill ${glyph}` : "";
  return `\\section*{${escapeLatex(title)}${suffix}}\n\\markboth{}{}\n`;
};

const renderSubhead = (title: string): string => `\\subhead{${escapeLatex(title)}}\n`;

const renderDivider = (): string => "\\constellationdivider\n";

const renderFigure = (attrs: Record<string, string>): string => {
  const caption = attrs.caption?.trim();
  const lines = [
    "\\vspace{1.5em}",
    "\\begin{center}",
    `\\input{../../diagrams/tikz/${attrs.name}.tikz}`,
    "\\end{center}",
  ];

  if (caption) {
    lines.push(`{\\centering\\small\\textit{${escapeLatex(caption)}}\\par}`);
  }

  lines.push("\\vspace{1.0em}");
  return `${lines.join("\n")}\n`;
};

const preprocessMdx = (body: string): string => {
  let markdown = body;

  markdown = markdown.replaceAll(/<section[^>]*>\s*/g, "");
  markdown = markdown.replaceAll(/\s*<\/section>/g, "");

  markdown = markdown.replaceAll(/<ConstellationDivider\s*\/>/g, `\n\n${renderDivider()}\n`);

  markdown = markdown.replaceAll(/<Figure\b[\s\S]*?\/>/g, (match) => {
    const attrs = parseAttributes(match);
    return `\n\n${renderFigure(attrs)}\n`;
  });

  markdown = markdown.replaceAll(/^##\s+(.+)$/gm, (_, title: string) => `\n\n${renderSection(title.trim())}\n`);
  markdown = markdown.replaceAll(/^###\s+(.+)$/gm, (_, title: string) => `\n\n${renderSubhead(title.trim())}\n`);

  return markdown
    .replaceAll("\\...", "...")
    .replaceAll(/\n{3,}/g, "\n\n")
    .trim()
    .concat("\n");
};

const markdownToLatex = (markdown: string): string => {
  const latex = execFileSync(
    "pandoc",
    ["-f", "markdown+footnotes+raw_tex", "-t", "latex", "--wrap=none"],
    { input: markdown, encoding: "utf8" },
  );

  return String(latex)
    .trim()
    .replaceAll("\\textbackslash{}", "\\")
    .replaceAll("\\textquotesingle{}", "'");
};

const buildTexDocument = (meta: Meta, body: string): string =>
  [
    "% Generated from src/content/essays/constellations/index.mdx",
    "% Do not edit this file directly; edit the MDX source instead.",
    "",
    "\\documentclass[11pt, oneside]{article}",
    "\\raggedbottom",
    "",
    "\\usepackage[",
    "    paperwidth=8.5in,",
    "    paperheight=11in,",
    "    left=1.3in,",
    "    right=1.3in,",
    "    top=1.1in,",
    "    bottom=1.1in",
    "]{geometry}",
    "",
    "\\makeatletter",
    "\\def\\input@path{{../}{../../}}",
    "\\makeatother",
    "\\usepackage[essay]{galileo}",
    "",
    "\\hypersetup{",
    `  pdftitle={${escapeLatex(meta.title)}},`,
    `  pdfauthor={${escapeLatex(meta.author)}},`,
    `  pdfsubject={${escapeLatex(meta.description)}},`,
    "  pdfkeywords={scientific operating system, scientific state, provenance, runtime, protocol}",
    "}",
    "",
    `\\newcommand{\\projectimprint}{${escapeLatex(meta.author)}}`,
    "\\newcommand{\\essayversion}{v1.0}",
    `\\newcommand{\\publicationdate}{${escapeLatex(meta.date)}}`,
    "\\newcommand{\\siteurl}{https://borrowedlight.org}",
    "",
    "\\usepackage[T1]{fontenc}",
    "\\usepackage[utf8]{inputenc}",
    "\\usepackage{mathpazo}",
    "\\usepackage{booktabs}",
    "\\usepackage{array}",
    "\\pgfdeclarelayer{background}",
    "\\pgfsetlayers{background,main}",
    "",
    "\\newcommand{\\subhead}[1]{%",
    "    \\vspace{1.2em}%",
    "    \\noindent\\textcolor{twilight}{\\textsc{#1}}%",
    "    \\vspace{0.4em}%",
    "    \\par\\noindent%",
    "}",
    "",
    "\\newcommand{\\glyphinheritance}{\\input{../../diagrams/tikz/glyphs/inheritance.tikz}}",
    "\\newcommand{\\glyphpattern}{\\input{../../diagrams/tikz/glyphs/pattern.tikz}}",
    "\\newcommand{\\glyphsoftware}{\\input{../../diagrams/tikz/glyphs/software.tikz}}",
    "\\newcommand{\\glyphconstellation}{\\input{../../diagrams/tikz/glyphs/constellation.tikz}}",
    "\\newcommand{\\glyphgigafactory}{\\input{../../diagrams/tikz/glyphs/gigafactory.tikz}}",
    "",
    "\\begin{document}",
    "",
    "\\thispagestyle{empty}",
    "\\pagecolor{paperivory}",
    "",
    "\\begin{tikzpicture}[remember picture, overlay]",
    "    \\shade[inner color=starglow, outer color=paperivory, opacity=0.20]",
    "        (current page.center) circle (5in);",
    "",
    "    \\begin{scope}[opacity=0.05]",
    "        \\fill[goldaccent] ([shift={(2.5cm,-4cm)}]current page.north west) circle (0.6pt);",
    "        \\fill[goldaccent] ([shift={(-3cm,-3cm)}]current page.north east) circle (0.5pt);",
    "        \\fill[goldaccent] ([shift={(3cm,4cm)}]current page.south west) circle (0.5pt);",
    "        \\fill[goldaccent] ([shift={(-2.5cm,5cm)}]current page.south east) circle (0.6pt);",
    "        \\fill[goldaccent] ([shift={(1.5cm,2cm)}]current page.center) circle (0.4pt);",
    "        \\fill[goldaccent] ([shift={(-4cm,-6cm)}]current page.north east) circle (0.4pt);",
    "        \\fill[goldaccent] ([shift={(5cm,3cm)}]current page.south west) circle (0.5pt);",
    "    \\end{scope}",
    "\\end{tikzpicture}",
    "",
    "\\vspace*{0.6in}",
    "",
    "\\begin{center}",
    "    \\scalebox{1.3}{\\input{../../diagrams/tikz/title-constellation.tikz}}",
    "",
    "    \\vspace{1.2cm}",
    "",
    "    {\\fontsize{42}{50}\\selectfont\\scshape\\textcolor{inkindigo}{Constellations}}",
    "",
    "    \\vspace{0.3cm}",
    "",
    "    {\\fontsize{14}{18}\\selectfont\\textcolor{twilight}{\\textit{of}}}",
    "",
    "    \\vspace{0.3cm}",
    "",
    "    {\\fontsize{42}{50}\\selectfont\\scshape\\textcolor{inkindigo}{Borrowed Light}}",
    "",
    "    \\vspace{1cm}",
    "",
    `    {\\fontsize{11.5}{16}\\selectfont\\color{twilight}\\textit{${escapeLatex(meta.subtitle)}}}`,
    "",
    "    \\vspace{0.8cm}",
    "",
    "    \\begin{tikzpicture}",
    "        \\begin{pgfonlayer}{background}",
    "        \\draw[goldaccent, line width=0.3pt, opacity=0.6] (-2.5,0) -- (-0.5,0);",
    "        \\draw[goldaccent, line width=0.3pt, opacity=0.6] (0.5,0) -- (2.5,0);",
    "        \\end{pgfonlayer}",
    "        \\fill[goldaccent, opacity=0.4] (-0.3,0) circle (1pt);",
    "        \\fill[goldaccent] (0,0) circle (1.8pt);",
    "        \\fill[goldaccent, opacity=0.4] (0.3,0) circle (1pt);",
    "    \\end{tikzpicture}",
    "",
    "    \\vspace{0.8cm}",
    "",
    "    \\vfill",
    "",
    "    {\\footnotesize\\textcolor{twilight}{\\projectimprint}}\\\\[0.2em]",
    "    {\\footnotesize\\textcolor{twilight}{\\essayversion\\ \\textbullet\\ \\publicationdate}}",
    "\\end{center}",
    "\\clearpage",
    "",
    "\\thispagestyle{empty}",
    "",
    "\\null",
    "\\vfill",
    "",
    "\\begin{center}",
    "\\begin{minipage}{0.75\\textwidth}",
    "\\centering",
    "{\\fontsize{14}{22}\\selectfont\\color{inkindigo}\\textit{``The inheritance from the master becomes not only his additions to the world's record but for his disciples the entire scaffolding by which they were erected.''}}",
    "\\end{minipage}",
    "",
    "\\vspace{2.5cm}",
    "",
    "{\\color{twilight}---\\hspace{0.3em}Vannevar Bush}\\\\[0.3cm]",
    "{\\small\\color{twilight}\\textit{As We May Think}, 1945}",
    "",
    "\\vspace{3cm}",
    "",
    "\\begin{tikzpicture}",
    "    \\shade[inner color=goldaccent, outer color=paperivory, opacity=0.06] (0,0) circle (12pt);",
    "    \\fill[goldaccent, opacity=0.5] (0,0) circle (2pt);",
    "\\end{tikzpicture}",
    "\\end{center}",
    "",
    "\\vfill",
    "\\vfill",
    "",
    "\\clearpage",
    "",
    body,
    "",
    "\\clearpage",
    "\\thispagestyle{empty}",
    "",
    "\\begin{tikzpicture}[remember picture, overlay]",
    "    \\shade[inner color=starglow, outer color=paperivory, opacity=0.22]",
    "        (current page.center) circle (5in);",
    "",
    "    \\begin{scope}[opacity=0.05]",
    "        \\fill[goldaccent] ([shift={(2.5cm,-4cm)}]current page.north west) circle (0.6pt);",
    "        \\fill[goldaccent] ([shift={(-3cm,-3cm)}]current page.north east) circle (0.5pt);",
    "        \\fill[goldaccent] ([shift={(3cm,4cm)}]current page.south west) circle (0.5pt);",
    "        \\fill[goldaccent] ([shift={(-2.5cm,5cm)}]current page.south east) circle (0.6pt);",
    "        \\fill[goldaccent] ([shift={(1.5cm,2cm)}]current page.center) circle (0.4pt);",
    "        \\fill[goldaccent] ([shift={(-4cm,-6cm)}]current page.north east) circle (0.4pt);",
    "        \\fill[goldaccent] ([shift={(5cm,3cm)}]current page.south west) circle (0.5pt);",
    "    \\end{scope}",
    "\\end{tikzpicture}",
    "",
    "\\vspace*{\\fill}",
    "",
    "\\begin{center}",
    "    \\scalebox{1.3}{\\input{../../diagrams/tikz/closing-constellation.tikz}}",
    "",
    "    \\vspace{2.5em}",
    "    \\textcolor{twilight}{\\textit{the light arrives}}",
    "\\end{center}",
    "",
    "\\vspace*{\\fill}",
    "",
    "\\end{document}",
    "",
  ].join("\n");

const main = () => {
  const mdxSource = readText(MDX_PATH);
  const { meta, body } = parseMeta(mdxSource);
  const preparedMarkdown = preprocessMdx(body);
  const renderedBody = markdownToLatex(preparedMarkdown);
  const tex = buildTexDocument(meta, renderedBody);

  writeFileSync(TEX_PATH, tex);
  console.log(`Exported ${path.relative(process.cwd(), TEX_PATH)} from MDX source.`);
};

main();
